default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST", "database") %>
  database: <%= ENV.fetch("DATABASE_NAME", "publicidade_development") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "wildfire") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

test:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST", "database") %>
  database: publicidade_test
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "wildfire") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>